version: "2"
services:
  master:
    build: ./ansible_master/
    image: eliesjebri/ansible_master
    container_name: master01
    hostname: master01
    ports:
      - "2220:22"
    command: ["/usr/sbin/sshd","-D"]
  host01:
    build: ./centos_base/
    image: ansible_host
    container_name: host01
    hostname: host01
    ports:
      - "2221:22"
    command: ["/usr/sbin/sshd","-D"]
  host02:
    image: ansible_host
    container_name: host02
    hostname: host02
    ports:
      - "2222:22"
    command: ["/usr/sbin/sshd","-D"]
  host03:
    image: ansible_host
    container_name: host03
    hostname: host03
    ports:
      - "2223:22"
    command: ["/usr/sbin/sshd","-D"]
